### ISSUE TITLE
Gliding is not working on new chrome version 

### ISSUE THREAD

**Issue by Droyk** [davidparsson/ScrollbarAnywhere#47]
So as the title says Gliding is not working because chrome enabled smooth scrolling plz fix it

**Comment by davidparsson** [comment]
Thanks for reporting. Which version of Chrome and what OS are you on? Which mouse button are you using to scroll?

**Comment by davidparsson** [comment]
After updating to `49.0.2623.87` I'm able to reproduce this myself as well, on Windows.

**Comment by Droyk** [comment]
[**@davidparsson**](https://github.com/davidparsson) commented on [Mar 12, 2016, 11:43 PM GMT+5:30](https://github.com/davidparsson/ScrollbarAnywhere/issues/47#issuecomment-195782444 "2016-03-12T18:13:45Z - Replied by Github Comment Enhancer"):
> After updating to `49.0.2623.87` I'm able to reproduce this myself as well, on Windows.

I always press left mouse button to scroll and this problem only occurs newer versions of chrome because chrome enable smooth scrolling 
I am rightnow using 49.0.2623.87 m (64-bit)

**Comment by Droyk** [comment]
[**@davidparsson**](https://github.com/davidparsson) commented on [Mar 12, 2016, 11:43 PM GMT+5:30](https://github.com/davidparsson/ScrollbarAnywhere/issues/47#issuecomment-195782444 "2016-03-12T18:13:45Z - Replied by Github Comment Enhancer"):
> After updating to `49.0.2623.87` I'm able to reproduce this myself as well, on Windows.

I always press left mouse button to scroll and this problem only occurs newer versions of chrome because chrome enable smooth scrolling 
I am rightnow using 49.0.2623.87 m (64-bit) and I am on windows 10

**Comment by davidparsson** [comment]
Fixed by 8e4455d. Released in 2.7.

**Comment by Droyk** [comment]
[**@davidparsson**](https://github.com/davidparsson) commented on [Mar 13, 2016, 7:27 PM GMT+5:30](https://github.com/davidparsson/scrollbar-anywhere/issues/47#issuecomment-195961417 "2016-03-13T13:57:22Z - Replied by Github Comment Enhancer"):
> Fixed by [<tt>8e4455d</tt>](https://github.com/davidparsson/ScrollbarAnywhere/commit/8e4455d8a1a2bfe7264a2e55facf892f694a0910). Released in 2.7.
**You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.**
Thanx for this and can you plz tell me why Your extension activate even when we are clicking on a element when the previous extension [Wet Banana](https://github.com/jedediah/wetbanana) doesn't 
why you didn't start wetbanana and make it more usable i know its not your but you can fork it and make changes to it and make it more usable......if you didn't have time then why you didn't start where the original developer left off by doing that you would have save some time and by this time you would have made wet banana an one of the best chrome extension

**Comment by davidparsson** [comment]
@Droyk, neither am I, so you're excused.

This _is_ actually a fork of Wet Banana, but I forked while the original maintainer was still active. The thing you're talking about is a bug, reported as #39. It seems to exist due to a change in Chrome's API.

**Comment by davidparsson** [comment]
@Droyk, it turns out that was a simple fix. I've released it in v2.8.

**Comment by Droyk** [comment]
[**@davidparsson**](https://github.com/davidparsson) commented on [Mar 14, 2016, 1:14 AM GMT+5:30](https://github.com/davidparsson/scrollbar-anywhere/issues/47#issuecomment-196034549 "2016-03-13T19:44:02Z - Replied by Github Comment Enhancer"):
> [@Droyk](https://github.com/Droyk), it turns out that was a simple fix. I've released it in v2.8.

Thanxx I didn't knew you can fix this issue this fast really thanxx but this issue still presist and it is full reproduce able If you goto reddit and clcik on one of the expando scrollbar extension enable automatically.

**Comment by davidparsson** [comment]
Thanks. Fixed in v2.9.

**Comment by Droyk** [comment]
[**@davidparsson**](https://github.com/davidparsson) commented on [Mar 14, 2016, 4:23 AM GMT+5:30](https://github.com/davidparsson/scrollbar-anywhere/issues/47#issuecomment-196076247 "2016-03-13T22:53:51Z - Replied by Github Comment Enhancer"):
> Thanks. Fixed in v2.9.

Thanx now its working and there is some problem I am having with first problem is speed 
speed is good but on some pages it becomes really really slow and laggy it only happens on when there is a lot of content on the page for example take reddit if there are thousands of comments I am browsing then I am going to see slowness and laggyness but if I scroll with scrollbar it will be fine can you plz tell me something to fi this issue

**Comment by davidparsson** [comment]
Hi again. I have two comments. First, please create new issues for new bug reports and feature requests. It makes tracking much easier. Discussion on this issue should going forward be limited to the gliding issue in Chrome v49+.

Second, I don't think there's much I can do in terms of performance, but without more details there is nothing at all I can do. For me performance is acceptable.

**Comment by davidparsson** [comment]
I've created #48. Please add any details you may have there.

**Comment by Droyk** [comment]
This issue still persists Sometimes clicking on the element doesn't activate the extension(which is good:smile:) sometimes it does and sometimes I have to double or tripe click the element to see something  means now even the element doesn't open on one click I have to make it open via double click or triple click

**Comment by davidparsson** [comment]
When you find a way to reproduce incorrect behavior, could you please
describe them in detail here? It might also be useful if you could enable
Scrollbar Anywhere's debug logging (in its options) and let me know what
messages are in the JavaScript console when that occurs. That might degrade
the performance, so I'd recommend you to only do that when you've found
actual problems. Thanks!
ons 16 mars 2016 kl 14:05 skrev Raiden <notifications@github.com>:

**Comment by Droyk** [comment]
okay this is the information I got 
![2nd time](https://cloud.githubusercontent.com/assets/15848350/13820132/059627e8-ebc2-11e5-9d59-98e0f5585fbc.png)
![1st time](https://cloud.githubusercontent.com/assets/15848350/13820133/05c9d868-ebc2-11e5-88cb-9b7d717db608.png)

**Comment by davidparsson** [comment]
Ok, thanks. Nothing unusual in those logs, though. I'm running out of ideas here... :confused:

**Comment by Droyk** [comment]
[**@davidparsson**](https://github.com/davidparsson) commented on [Mar 17, 2016, 5:51 PM GMT+5:30](https://github.com/davidparsson/scrollbar-anywhere/issues/47#issuecomment-197854459 "2016-03-17T12:21:25Z - Replied by Github Comment Enhancer"):
> Ok, thanks. Nothing unusual in those logs, though. I'm running out of ideas here... ![:confused:](https://assets-cdn.github.com/images/icons/emoji/unicode/1f615.png ":confused:")

Well I think you are not seeing this log correctly ![2nd time](https://cloud.githubusercontent.com/assets/15848350/13820132/059627e8-ebc2-11e5-9d59-98e0f5585fbc.png)

this should be the only thing that should come up on log when I am clicking an element 
![screenshot_20160317180805](https://cloud.githubusercontent.com/assets/15848350/13846284/eb800252-ec6b-11e5-8840-dd8c42b7c2fb.png)

but it is not .....Don't you think there is something wrong with this

**Comment by Droyk** [comment]
This issue still persist On torrent freak comment section 
I made a video to explain it to you 
https://streamable.com/5gid 
took me 5 minutes plz fix this issue

**Comment by davidparsson** [comment]
Neither scrolling nor gliding works there, so that's actually another issue. I've created #49 to describe that.
